//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubberduck.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RubberduckUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RubberduckUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rubberduck.Resources.RubberduckUI", typeof(RubberduckUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddClass {
            get {
                object obj = ResourceManager.GetObject("AddClass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddForm {
            get {
                object obj = ResourceManager.GetObject("AddForm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddModule {
            get {
                object obj = ResourceManager.GetObject("AddModule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementations of &apos;{0}&apos;.
        /// </summary>
        public static string AllImplementations_Caption {
            get {
                return ResourceManager.GetString("AllImplementations_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class or member &apos;{0}&apos; is not implemented..
        /// </summary>
        public static string AllImplementations_NoneFound {
            get {
                return ResourceManager.GetString("AllImplementations_NoneFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All references: &apos;{0}&apos;.
        /// </summary>
        public static string AllReferences_Caption {
            get {
                return ResourceManager.GetString("AllReferences_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No references were found for identifier &apos;{0}&apos;..
        /// </summary>
        public static string AllReferences_NoneFound {
            get {
                return ResourceManager.GetString("AllReferences_NoneFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No uses were found for project reference &apos;{0}&apos;..
        /// </summary>
        public static string AllReferences_NoneFoundReference {
            get {
                return ResourceManager.GetString("AllReferences_NoneFoundReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for uses of reference &apos;{0}&apos; has returned {1} results. Displaying them may negatively impact performance. Continue?.
        /// </summary>
        public static string AllReferences_PerformanceWarning {
            get {
                return ResourceManager.GetString("AllReferences_PerformanceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplyButtonText {
            get {
                return ResourceManager.GetString("ApplyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_090 {
            get {
                object obj = ResourceManager.GetObject("arrow_090", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_090_dimmed {
            get {
                object obj = ResourceManager.GetObject("arrow_090_dimmed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_270 {
            get {
                object obj = ResourceManager.GetObject("arrow_270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_270_dimmed {
            get {
                object obj = ResourceManager.GetObject("arrow_270_dimmed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_circle_double {
            get {
                object obj = ResourceManager.GetObject("arrow_circle_double", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BrokenReference {
            get {
                object obj = ResourceManager.GetObject("BrokenReference", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clock_select {
            get {
                object obj = ResourceManager.GetObject("clock_select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clock_select_pinned {
            get {
                object obj = ResourceManager.GetObject("clock_select_pinned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} {3} {4} {5}.
        /// </summary>
        public static string CodeExplorer_IExportable_DeclarationFormat {
            get {
                return ResourceManager.GetString("CodeExplorer_IExportable_DeclarationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to selected issue.
        /// </summary>
        public static string CodeInspections_GoToolTip {
            get {
                return ResourceManager.GetString("CodeInspections_GoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to next issue.
        /// </summary>
        public static string CodeInspections_NextToolTip {
            get {
                return ResourceManager.GetString("CodeInspections_NextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to previous issue.
        /// </summary>
        public static string CodeInspections_PreviousToolTip {
            get {
                return ResourceManager.GetString("CodeInspections_PreviousToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address the issue.
        /// </summary>
        public static string CodeInspections_QuickFixToolTip {
            get {
                return ResourceManager.GetString("CodeInspections_QuickFixToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run code inspections.
        /// </summary>
        public static string CodeInspections_RefreshToolTip {
            get {
                return ResourceManager.GetString("CodeInspections_RefreshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run code inspections.
        /// </summary>
        public static string CodeInspections_Run {
            get {
                return ResourceManager.GetString("CodeInspections_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code _Inspections.
        /// </summary>
        public static string CodeInspectionsWindowSettings_AccessKey {
            get {
                return ResourceManager.GetString("CodeInspectionsWindowSettings_AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Explorer.
        /// </summary>
        public static string CommandDescription_CodeExplorerCommand {
            get {
                return ResourceManager.GetString("CommandDescription_CodeExplorerCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor / Rename.
        /// </summary>
        public static string CommandDescription_CodePaneRefactorRenameCommand {
            get {
                return ResourceManager.GetString("CommandDescription_CodePaneRefactorRenameCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export active project.
        /// </summary>
        public static string CommandDescription_ExportAllCommand {
            get {
                return ResourceManager.GetString("CommandDescription_ExportAllCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find symbol.
        /// </summary>
        public static string CommandDescription_FindSymbolCommand {
            get {
                return ResourceManager.GetString("CommandDescription_FindSymbolCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent Module.
        /// </summary>
        public static string CommandDescription_IndentCurrentModuleCommand {
            get {
                return ResourceManager.GetString("CommandDescription_IndentCurrentModuleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent Procedure.
        /// </summary>
        public static string CommandDescription_IndentCurrentProcedureCommand {
            get {
                return ResourceManager.GetString("CommandDescription_IndentCurrentProcedureCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Inspections.
        /// </summary>
        public static string CommandDescription_InspectionResultsCommand {
            get {
                return ResourceManager.GetString("CommandDescription_InspectionResultsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peek definition.
        /// </summary>
        public static string CommandDescription_PeekDefinitionCommand {
            get {
                return ResourceManager.GetString("CommandDescription_PeekDefinitionCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor / Encapsulate Field.
        /// </summary>
        public static string CommandDescription_RefactorEncapsulateFieldCommand {
            get {
                return ResourceManager.GetString("CommandDescription_RefactorEncapsulateFieldCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor / Extract Method.
        /// </summary>
        public static string CommandDescription_RefactorExtractMethodCommand {
            get {
                return ResourceManager.GetString("CommandDescription_RefactorExtractMethodCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor / Move declaration closer to usage.
        /// </summary>
        public static string CommandDescription_RefactorMoveCloserToUsageCommand {
            get {
                return ResourceManager.GetString("CommandDescription_RefactorMoveCloserToUsageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh parser state.
        /// </summary>
        public static string CommandDescription_ReparseCommand {
            get {
                return ResourceManager.GetString("CommandDescription_ReparseCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Explorer.
        /// </summary>
        public static string CommandDescription_TestExplorerCommand {
            get {
                return ResourceManager.GetString("CommandDescription_TestExplorerCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook is already attached..
        /// </summary>
        public static string CommonHotkey_HookAttached {
            get {
                return ResourceManager.GetString("CommonHotkey_HookAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook is already detached..
        /// </summary>
        public static string CommonHotkey_HookDetached {
            get {
                return ResourceManager.GetString("CommonHotkey_HookDetached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key..
        /// </summary>
        public static string CommonHotkey_InvalidKey {
            get {
                return ResourceManager.GetString("CommonHotkey_InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey ({0}) not registered..
        /// </summary>
        public static string CommonHotkey_KeyNotRegistered {
            get {
                return ResourceManager.GetString("CommonHotkey_KeyNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        public static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveX Designer.
        /// </summary>
        public static string ComponentType_ActiveXDesigner {
            get {
                return ResourceManager.GetString("ComponentType_ActiveXDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Module.
        /// </summary>
        public static string ComponentType_ClassModule {
            get {
                return ResourceManager.GetString("ComponentType_ClassModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM component.
        /// </summary>
        public static string ComponentType_ComComponent {
            get {
                return ResourceManager.GetString("ComponentType_ComComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Object.
        /// </summary>
        public static string ComponentType_DocObject {
            get {
                return ResourceManager.GetString("ComponentType_DocObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Module.
        /// </summary>
        public static string ComponentType_Document {
            get {
                return ResourceManager.GetString("ComponentType_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDI Form.
        /// </summary>
        public static string ComponentType_MDIForm {
            get {
                return ResourceManager.GetString("ComponentType_MDIForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Page.
        /// </summary>
        public static string ComponentType_PropPage {
            get {
                return ResourceManager.GetString("ComponentType_PropPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Document.
        /// </summary>
        public static string ComponentType_RelatedDocument {
            get {
                return ResourceManager.GetString("ComponentType_RelatedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource File.
        /// </summary>
        public static string ComponentType_ResFile {
            get {
                return ResourceManager.GetString("ComponentType_ResFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Module.
        /// </summary>
        public static string ComponentType_StandardModule {
            get {
                return ResourceManager.GetString("ComponentType_StandardModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        public static string ComponentType_Undefined {
            get {
                return ResourceManager.GetString("ComponentType_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Control.
        /// </summary>
        public static string ComponentType_UserControl {
            get {
                return ResourceManager.GetString("ComponentType_UserControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserForm.
        /// </summary>
        public static string ComponentType_UserForm {
            get {
                return ResourceManager.GetString("ComponentType_UserForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VB Form.
        /// </summary>
        public static string ComponentType_VBForm {
            get {
                return ResourceManager.GetString("ComponentType_VBForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; is assigned. Remove assignment instruction(s)?.
        /// </summary>
        public static string ConfirmRemoveAssignmentWithUnusedDeclaration {
            get {
                return ResourceManager.GetString("ConfirmRemoveAssignmentWithUnusedDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiple controls.
        /// </summary>
        public static string ContextMultipleControlsSelection {
            get {
                return ResourceManager.GetString("ContextMultipleControlsSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to references.
        /// </summary>
        public static string ContextReferences {
            get {
                return ResourceManager.GetString("ContextReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cross_circle {
            get {
                object obj = ResourceManager.GetObject("cross_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cross_script {
            get {
                object obj = ResourceManager.GetObject("cross_script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.
        /// </summary>
        public static string DeclarationType_Document {
            get {
                return ResourceManager.GetString("DeclarationType_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        public static string DeselectAll_Button {
            get {
                return ResourceManager.GetString("DeselectAll_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap edit_size {
            get {
                object obj = ResourceManager.GetObject("edit_size", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to parse and process the projects in the VBE..
        /// </summary>
        public static string EmptyUIRefreshMessage {
            get {
                return ResourceManager.GetString("EmptyUIRefreshMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubberduck doesn&apos;t see anything yet..
        /// </summary>
        public static string EmptyUIRefreshMessage_Title {
            get {
                return ResourceManager.GetString("EmptyUIRefreshMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute.
        /// </summary>
        public static string EndOfLineCommentStyle_Absolute {
            get {
                return ResourceManager.GetString("EndOfLineCommentStyle_Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align In Column.
        /// </summary>
        public static string EndOfLineCommentStyle_AlignInColumn {
            get {
                return ResourceManager.GetString("EndOfLineCommentStyle_AlignInColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Gap.
        /// </summary>
        public static string EndOfLineCommentStyle_SameGap {
            get {
                return ResourceManager.GetString("EndOfLineCommentStyle_SameGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Gap.
        /// </summary>
        public static string EndOfLineCommentStyle_StandardGap {
            get {
                return ResourceManager.GetString("EndOfLineCommentStyle_StandardGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap exclamation {
            get {
                object obj = ResourceManager.GetObject("exclamation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap exclamation_pinned {
            get {
                object obj = ResourceManager.GetObject("exclamation_pinned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to export the source of {0} to:.
        /// </summary>
        public static string ExportAllCommand_SaveAsDialog_Title {
            get {
                return ResourceManager.GetString("ExportAllCommand_SaveAsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find symbol.
        /// </summary>
        public static string FindSymbolDialog_Caption {
            get {
                return ResourceManager.GetString("FindSymbolDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix.
        /// </summary>
        public static string Fix {
            get {
                return ResourceManager.GetString("Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        public static string GroupingGrid_GroupingStyle {
            get {
                return ResourceManager.GetString("GroupingGrid_GroupingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By category.
        /// </summary>
        public static string GroupingStyle_ByCategory {
            get {
                return ResourceManager.GetString("GroupingStyle_ByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By inspection type.
        /// </summary>
        public static string GroupingStyle_ByInspectionType {
            get {
                return ResourceManager.GetString("GroupingStyle_ByInspectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By location.
        /// </summary>
        public static string GroupingStyle_ByLocation {
            get {
                return ResourceManager.GetString("GroupingStyle_ByLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By marker.
        /// </summary>
        public static string GroupingStyle_ByMarker {
            get {
                return ResourceManager.GetString("GroupingStyle_ByMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By inspection.
        /// </summary>
        public static string GroupingStyle_ByName {
            get {
                return ResourceManager.GetString("GroupingStyle_ByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By outcome.
        /// </summary>
        public static string GroupingStyle_ByOutcome {
            get {
                return ResourceManager.GetString("GroupingStyle_ByOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By severity.
        /// </summary>
        public static string GroupingStyle_BySeverity {
            get {
                return ResourceManager.GetString("GroupingStyle_BySeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hourglass {
            get {
                object obj = ResourceManager.GetObject("hourglass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Project.
        /// </summary>
        public static string IndentCurrentProject {
            get {
                return ResourceManager.GetString("IndentCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect.
        /// </summary>
        public static string Inspect {
            get {
                return ResourceManager.GetString("Inspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        public static string InspectionResults_CollapseAll {
            get {
                return ResourceManager.GetString("InspectionResults_CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all.
        /// </summary>
        public static string InspectionResults_ExpandAll {
            get {
                return ResourceManager.GetString("InspectionResults_ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        public static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string Language_CS {
            get {
                return ResourceManager.GetString("Language_CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Language_DE {
            get {
                return ResourceManager.GetString("Language_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language_EN {
            get {
                return ResourceManager.GetString("Language_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string Language_ES {
            get {
                return ResourceManager.GetString("Language_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string Language_FR {
            get {
                return ResourceManager.GetString("Language_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Language_IT {
            get {
                return ResourceManager.GetString("Language_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap light_bulb_code {
            get {
                object obj = ResourceManager.GetObject("light_bulb_code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Rubberduck Configuration.
        /// </summary>
        public static string LoadConfigError {
            get {
                return ResourceManager.GetString("LoadConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap lock_pinned {
            get {
                object obj = ResourceManager.GetObject("lock_pinned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LockedReference {
            get {
                object obj = ResourceManager.GetObject("LockedReference", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap magnifier_medium {
            get {
                object obj = ResourceManager.GetObject("magnifier_medium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make ActiveSheet reference explicit.
        /// </summary>
        public static string MakeActiveSheetReferenceExplicit {
            get {
                return ResourceManager.GetString("MakeActiveSheetReferenceExplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make ActiveWorkbook reference explicit.
        /// </summary>
        public static string MakeActiveWorkbookReferenceExplicit {
            get {
                return ResourceManager.GetString("MakeActiveWorkbookReferenceExplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier &apos;{0}&apos; will trigger a &apos;Use Meaningful Name&apos; inspection result..
        /// </summary>
        public static string MeaninglessNameCriteriaMatchFormat {
            get {
                return ResourceManager.GetString("MeaninglessNameCriteriaMatchFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Attribute Recovery Failure.
        /// </summary>
        public static string MemberAttributeRecoveryFailureCaption {
            get {
                return ResourceManager.GetString("MemberAttributeRecoveryFailureCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member attributes for the following modules could not be recovered because they could no longer be found. {0}.
        /// </summary>
        public static string MemberAttributeRecoveryMembersNotFoundMessage {
            get {
                return ResourceManager.GetString("MemberAttributeRecoveryMembersNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to recover member attributes..
        /// </summary>
        public static string MemberAttributeRecoveryRewriteFailedMessage {
            get {
                return ResourceManager.GetString("MemberAttributeRecoveryRewriteFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap minus_white {
            get {
                object obj = ResourceManager.GetObject("minus_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module options should be specified first.
        /// </summary>
        public static string ModuleOptionsNotSpecifiedFirst {
            get {
                return ResourceManager.GetString("ModuleOptionsNotSpecifiedFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameLabelText {
            get {
                return ResourceManager.GetString("NameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate.
        /// </summary>
        public static string Navigate {
            get {
                return ResourceManager.GetString("Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK_AllCaps {
            get {
                return ResourceManager.GetString("OK_AllCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap padlock {
            get {
                object obj = ResourceManager.GetObject("padlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubberduck - Parser Errors.
        /// </summary>
        public static string ParseErrors_Caption {
            get {
                return ResourceManager.GetString("ParseErrors_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing &apos;{0}&apos;....
        /// </summary>
        public static string ParseProgress {
            get {
                return ResourceManager.GetString("ParseProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser Errors.
        /// </summary>
        public static string Parser_ParserError {
            get {
                return ResourceManager.GetString("Parser_ParserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} module(s) failed to parse; click for details..
        /// </summary>
        public static string ParserErrorToolTipText {
            get {
                return ResourceManager.GetString("ParserErrorToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ParserProgress_ShowDetails {
            get {
                return ResourceManager.GetString("ParserProgress_ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string ParserState_Busy {
            get {
                return ResourceManager.GetString("ParserState_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse Error.
        /// </summary>
        public static string ParserState_Error {
            get {
                return ResourceManager.GetString("ParserState_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading references.
        /// </summary>
        public static string ParserState_LoadingReference {
            get {
                return ResourceManager.GetString("ParserState_LoadingReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed.
        /// </summary>
        public static string ParserState_Parsed {
            get {
                return ResourceManager.GetString("ParserState_Parsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing….
        /// </summary>
        public static string ParserState_Parsing {
            get {
                return ResourceManager.GetString("ParserState_Parsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string ParserState_Pending {
            get {
                return ResourceManager.GetString("ParserState_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string ParserState_Ready {
            get {
                return ResourceManager.GetString("ParserState_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolver Error.
        /// </summary>
        public static string ParserState_ResolverError {
            get {
                return ResourceManager.GetString("ParserState_ResolverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving declarations....
        /// </summary>
        public static string ParserState_ResolvingDeclarations {
            get {
                return ResourceManager.GetString("ParserState_ResolvingDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving references....
        /// </summary>
        public static string ParserState_ResolvingReferences {
            get {
                return ResourceManager.GetString("ParserState_ResolvingReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string ParserState_Started {
            get {
                return ResourceManager.GetString("ParserState_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        public static string ParserState_UnexpectedError {
            get {
                return ResourceManager.GetString("ParserState_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing project components....
        /// </summary>
        public static string ParseStarted {
            get {
                return ResourceManager.GetString("ParseStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (parsing...).
        /// </summary>
        public static string Parsing {
            get {
                return ResourceManager.GetString("Parsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no description annotation or attribute).
        /// </summary>
        public static string PeekDefinition_DefaultDescription {
            get {
                return ResourceManager.GetString("PeekDefinition_DefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peek definition.
        /// </summary>
        public static string PeekDefinitionCommandText {
            get {
                return ResourceManager.GetString("PeekDefinitionCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Warning.
        /// </summary>
        public static string PerformanceWarningCaption {
            get {
                return ResourceManager.GetString("PerformanceWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pinned {
            get {
                object obj = ResourceManager.GetObject("pinned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap plus_circle {
            get {
                object obj = ResourceManager.GetObject("plus_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap plus_circle_pinned {
            get {
                object obj = ResourceManager.GetObject("plus_circle_pinned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ProjectForm {
            get {
                object obj = ResourceManager.GetObject("ProjectForm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection is not a variable..
        /// </summary>
        public static string PromoteVariable_InvalidSelection {
            get {
                return ResourceManager.GetString("PromoteVariable_InvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///{1}
        ///
        ///{2}
        ///
        ///Would you like to restore default configuration?
        ///Warning: All customized settings will be lost.  Your old file will be saved in &apos;{3}&apos;..
        /// </summary>
        public static string PromptLoadDefaultConfig {
            get {
                return ResourceManager.GetString("PromptLoadDefaultConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap question_white {
            get {
                object obj = ResourceManager.GetObject("question_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to fix broken references.
        /// </summary>
        public static string ReferenceSettings_FixBroken {
            get {
                return ResourceManager.GetString("ReferenceSettings_FixBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for project folder.
        /// </summary>
        public static string ReferenceSettings_FolderDialogHeader {
            get {
                return ResourceManager.GetString("ReferenceSettings_FolderDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Directories.
        /// </summary>
        public static string ReferenceSettings_FoldersHeader {
            get {
                return ResourceManager.GetString("ReferenceSettings_FoldersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent references tracked:.
        /// </summary>
        public static string ReferenceSettings_RecentTracked {
            get {
                return ResourceManager.GetString("ReferenceSettings_RecentTracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track references not added by Rubberduck.
        /// </summary>
        public static string ReferenceSettings_TrackHostReferences {
            get {
                return ResourceManager.GetString("ReferenceSettings_TrackHostReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParamArray parameter must be specified last..
        /// </summary>
        public static string ReorderPresenter_ParamArrayError {
            get {
                return ResourceManager.GetString("ReorderPresenter_ParamArrayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. Click to refresh..
        /// </summary>
        public static string ReparseToolTipText {
            get {
                return ResourceManager.GetString("ReparseToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the contents of project &apos;{0}&apos; and replace them with the contents of the selected files?.
        /// </summary>
        public static string ReplaceProjectContentsFromFilesCommand_ConfirmationMessage {
            get {
                return ResourceManager.GetString("ReplaceProjectContentsFromFilesCommand_ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Project Content from Files.
        /// </summary>
        public static string ReplaceProjectContentsFromFilesCommand_DialogCaption {
            get {
                return ResourceManager.GetString("ReplaceProjectContentsFromFilesCommand_DialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving....
        /// </summary>
        public static string ResolutionProgress {
            get {
                return ResourceManager.GetString("ResolutionProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubberduck.
        /// </summary>
        public static string Rubberduck {
            get {
                return ResourceManager.GetString("Rubberduck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string Rubberduck_AboutBuild {
            get {
                return ResourceManager.GetString("Rubberduck_AboutBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse all opened projects.
        /// </summary>
        public static string RubberduckCommandbarRefreshButtonTooltip {
            get {
                return ResourceManager.GetString("RubberduckCommandbarRefreshButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubberduck encountered an error. Please save your work and restart the host program; if logging is enabled, you can upload your log file located at &apos;%AppData%Roaming\Rubberduck\Logs\RubberduckLog.txt&apos; to a GitHub issue at &apos;https://github.com/rubberduck-vba/Rubberduck/issues/new&apos; and report the bug..
        /// </summary>
        public static string RubberduckFatalError {
            get {
                return ResourceManager.GetString("RubberduckFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubberduck Add-In could not be loaded.
        /// </summary>
        public static string RubberduckLoadFailure {
            get {
                return ResourceManager.GetString("RubberduckLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolwindows were not correctly destroyed and/or could not be recreated; the VBE may not be in a stable state. Rubberduck will load normally next time the VBE is initialized..
        /// </summary>
        public static string RubberduckReloadFailure_Message {
            get {
                return ResourceManager.GetString("RubberduckReloadFailure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubberduck will not reload.
        /// </summary>
        public static string RubberduckReloadFailure_Title {
            get {
                return ResourceManager.GetString("RubberduckReloadFailure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Close.
        /// </summary>
        public static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All implementations: &apos;{0}&apos;.
        /// </summary>
        public static string SearchResults_AllImplementationsTabFormat {
            get {
                return ResourceManager.GetString("SearchResults_AllImplementationsTabFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All references: &apos;{0}&apos;.
        /// </summary>
        public static string SearchResults_AllReferencesTabFormat {
            get {
                return ResourceManager.GetString("SearchResults_AllReferencesTabFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResults_Caption {
            get {
                return ResourceManager.GetString("SearchResults_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        public static string SearchResults_Context {
            get {
                return ResourceManager.GetString("SearchResults_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string SearchResults_Location {
            get {
                return ResourceManager.GetString("SearchResults_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string SearchResults_MemberName {
            get {
                return ResourceManager.GetString("SearchResults_MemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string SearchResults_MemberType {
            get {
                return ResourceManager.GetString("SearchResults_MemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string SearchResults_ModuleName {
            get {
                return ResourceManager.GetString("SearchResults_ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll_Button {
            get {
                return ResourceManager.GetString("SelectAll_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        public static string Severity {
            get {
                return ResourceManager.GetString("Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity:.
        /// </summary>
        public static string SeverityLabelText {
            get {
                return ResourceManager.GetString("SeverityLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap skull_mad {
            get {
                object obj = ResourceManager.GetObject("skull_mad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Indenter settings were found in your registry.
        ///Would you like to import them to Rubberduck?.
        /// </summary>
        public static string SmartIndenter_LegacySettingPrompt {
            get {
                return ResourceManager.GetString("SmartIndenter_LegacySettingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Splash {
            get {
                object obj = ResourceManager.GetObject("Splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SyncArrows {
            get {
                object obj = ResourceManager.GetObject("SyncArrows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubberduck Test Results - {0}.
        /// </summary>
        public static string TestExplorer_AppendHeader {
            get {
                return ResourceManager.GetString("TestExplorer_AppendHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tick_circle {
            get {
                object obj = ResourceManager.GetObject("tick_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tick_circle_pinned {
            get {
                object obj = ResourceManager.GetObject("tick_circle_pinned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUG.
        /// </summary>
        public static string TodoMarkerBug {
            get {
                return ResourceManager.GetString("TodoMarkerBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE.
        /// </summary>
        public static string TodoMarkerNote {
            get {
                return ResourceManager.GetString("TodoMarkerNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string TodoMarkerTodo {
            get {
                return ResourceManager.GetString("TodoMarkerTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Components from Files.
        /// </summary>
        public static string UpdateFromFilesCommand_DialogCaption {
            get {
                return ResourceManager.GetString("UpdateFromFilesCommand_DialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component type of the existing component &apos;{0}&apos; does not agree with that indicated by the extension of file &apos;{1}&apos;.
        ///
        ///Import aborted..
        /// </summary>
        public static string UpdateFromFilesCommand_DifferentComponentType {
            get {
                return ResourceManager.GetString("UpdateFromFilesCommand_DifferentComponentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pre-release.
        /// </summary>
        public static string VersionCheck_BuildType_PreRelease {
            get {
                return ResourceManager.GetString("VersionCheck_BuildType_PreRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to release.
        /// </summary>
        public static string VersionCheck_BuildType_Release {
            get {
                return ResourceManager.GetString("VersionCheck_BuildType_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently running Rubberduck version {0}.
        ///Good news! Version {1} ({2}) is now available.
        ///
        ///To review the change log and manually upgrade Rubberduck, click &apos;Yes&apos;.
        ///
        ///This dialog is showing because version checks are enabled. You can turn off this feature in Rubberduck &gt; Settings..
        /// </summary>
        public static string VersionCheck_NewVersionAvailable {
            get {
                return ResourceManager.GetString("VersionCheck_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window visibility at startup.
        /// </summary>
        public static string WindowSettings_StartupVisibilityHeader {
            get {
                return ResourceManager.GetString("WindowSettings_StartupVisibilityHeader", resourceCulture);
            }
        }
    }
}
