//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubberduck.SourceControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceControlText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceControlText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rubberduck.SourceControl.SourceControlText", typeof(SourceControlText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch deletion failed..
        /// </summary>
        internal static string GitBranchDeleteFailed {
            get {
                return ResourceManager.GetString("GitBranchDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout failed..
        /// </summary>
        internal static string GitCheckoutFailed {
            get {
                return ResourceManager.GetString("GitCheckoutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit failed..
        /// </summary>
        internal static string GitCommitFailed {
            get {
                return ResourceManager.GetString("GitCommitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch failed..
        /// </summary>
        internal static string GitFetchFailed {
            get {
                return ResourceManager.GetString("GitFetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stage file..
        /// </summary>
        internal static string GitFileStageFailed {
            get {
                return ResourceManager.GetString("GitFileStageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stage file &apos;{0}&apos;.
        /// </summary>
        internal static string GitFileStageFailedMsg {
            get {
                return ResourceManager.GetString("GitFileStageFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch creation failed..
        /// </summary>
        internal static string GitNewBranchFailed {
            get {
                return ResourceManager.GetString("GitNewBranchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform initial commit..
        /// </summary>
        internal static string GitNoInitialCommit {
            get {
                return ResourceManager.GetString("GitNoInitialCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize repository..
        /// </summary>
        internal static string GitNotInit {
            get {
                return ResourceManager.GetString("GitNotInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish failed..
        /// </summary>
        internal static string GitPublishFailed {
            get {
                return ResourceManager.GetString("GitPublishFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull failed..
        /// </summary>
        internal static string GitPullFailed {
            get {
                return ResourceManager.GetString("GitPullFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push failed..
        /// </summary>
        internal static string GitPushFailed {
            get {
                return ResourceManager.GetString("GitPushFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove file &apos;{0}&apos; from staging area..
        /// </summary>
        internal static string GitRemoveFileStaging {
            get {
                return ResourceManager.GetString("GitRemoveFileStaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to clone remote repository..
        /// </summary>
        internal static string GitRepoNotCloned {
            get {
                return ResourceManager.GetString("GitRepoNotCloned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository not found..
        /// </summary>
        internal static string GitRepoNotFound {
            get {
                return ResourceManager.GetString("GitRepoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve repository status..
        /// </summary>
        internal static string GitRepoStatusFailed {
            get {
                return ResourceManager.GetString("GitRepoStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert resulted in conflicts. Revert failed..
        /// </summary>
        internal static string GitRevertConflict {
            get {
                return ResourceManager.GetString("GitRevertConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert failed..
        /// </summary>
        internal static string GitRevertFailed {
            get {
                return ResourceManager.GetString("GitRevertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo failed..
        /// </summary>
        internal static string GitUndoFailed {
            get {
                return ResourceManager.GetString("GitUndoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublish failed..
        /// </summary>
        internal static string GitUnpublishFailed {
            get {
                return ResourceManager.GetString("GitUnpublishFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be a project open for Rubberduck to successfully initialize a repository..
        /// </summary>
        internal static string NoProjectOpen {
            get {
                return ResourceManager.GetString("NoProjectOpen", resourceCulture);
            }
        }
    }
}
