//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubberduck.Resources.About {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rubberduck.Resources.About.AboutUI", typeof(AboutUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing powered by ANTLR
        ///Syntax highlighting powered by AvalonEdit
        ///Native hooks powered by EasyHook
        ///Fugue icons by Yusuke Kamiyamane
        ///IDE icons from SharpDevelop
        ///WPF localization support by Grant Frisken.
        /// </summary>
        public static string AboutWindow_AttributionList {
            get {
                return ResourceManager.GetString("AboutWindow_AttributionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributions.
        /// </summary>
        public static string AboutWindow_AttributionsLabel {
            get {
                return ResourceManager.GetString("AboutWindow_AttributionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogs:.
        /// </summary>
        public static string AboutWindow_BlogsHeader {
            get {
                return ResourceManager.GetString("AboutWindow_BlogsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Rubberduck.
        /// </summary>
        public static string AboutWindow_Caption {
            get {
                return ResourceManager.GetString("AboutWindow_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community:.
        /// </summary>
        public static string AboutWindow_CommunityHeader {
            get {
                return ResourceManager.GetString("AboutWindow_CommunityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors &amp; supporters:.
        /// </summary>
        public static string AboutWindow_ContributorsHeader {
            get {
                return ResourceManager.GetString("AboutWindow_ContributorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Copyright 2014-{0} Rubberduck project contributors.
        /// </summary>
        public static string AboutWindow_Copyright {
            get {
                return ResourceManager.GetString("AboutWindow_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy version info.
        /// </summary>
        public static string AboutWindow_CopyVersionCaption {
            get {
                return ResourceManager.GetString("AboutWindow_CopyVersionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy version information to clipboard.
        /// </summary>
        public static string AboutWindow_CopyVersionLabel {
            get {
                return ResourceManager.GetString("AboutWindow_CopyVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version information was copied to clipboard..
        /// </summary>
        public static string AboutWindow_CopyVersionMessage {
            get {
                return ResourceManager.GetString("AboutWindow_CopyVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also find us at:.
        /// </summary>
        public static string AboutWindow_FindRubberduckAt {
            get {
                return ResourceManager.GetString("AboutWindow_FindRubberduckAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found an issue?.
        /// </summary>
        public static string AboutWindow_FoundAnIssue {
            get {
                return ResourceManager.GetString("AboutWindow_FoundAnIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All contributors to our GitHub repository
        ///All our stargazers, likers &amp; followers, for the warm fuzzies
        ///...and anyone reading this!.
        /// </summary>
        public static string AboutWindow_GeneralThanks {
            get {
                return ResourceManager.GetString("AboutWindow_GeneralThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us improve Rubberduck!.
        /// </summary>
        public static string AboutWindow_HelpImproveRubberduck {
            get {
                return ResourceManager.GetString("AboutWindow_HelpImproveRubberduck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Executable: {0}.
        /// </summary>
        public static string AboutWindow_HostExecutable {
            get {
                return ResourceManager.GetString("AboutWindow_HostExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Product: {0} {1}.
        /// </summary>
        public static string AboutWindow_HostProduct {
            get {
                return ResourceManager.GetString("AboutWindow_HostProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Version: {0}.
        /// </summary>
        public static string AboutWindow_HostVersion {
            get {
                return ResourceManager.GetString("AboutWindow_HostVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS: {0}, {1}.
        /// </summary>
        public static string AboutWindow_OperatingSystem {
            get {
                return ResourceManager.GetString("AboutWindow_OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an issue.
        /// </summary>
        public static string AboutWindow_ReportAnIssue {
            get {
                return ResourceManager.GetString("AboutWindow_ReportAnIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Thanks.
        /// </summary>
        public static string AboutWindow_SpecialThanksLabel {
            get {
                return ResourceManager.GetString("AboutWindow_SpecialThanksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View log in File Explorer.
        /// </summary>
        public static string AboutWindow_ViewLogLabel {
            get {
                return ResourceManager.GetString("AboutWindow_ViewLogLabel", resourceCulture);
            }
        }
    }
}
