VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CMemberInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public Bindable As Boolean
Attribute Bindable.VB_VarUserMemId = 1073938432
Public Browsable As Boolean
Attribute Browsable.VB_VarUserMemId = 1073938433
Public Category As String
Attribute Category.VB_VarUserMemId = 1073938434
Public DefaultBind As Boolean
Attribute DefaultBind.VB_VarUserMemId = 1073938435
Public Description As String
Attribute Description.VB_VarUserMemId = 1073938436
Public DisplayBind As Boolean
Attribute DisplayBind.VB_VarUserMemId = 1073938437
Public HelpContextID As String
Attribute HelpContextID.VB_VarUserMemId = 1073938438
Public Hidden As Boolean
Attribute Hidden.VB_VarUserMemId = 1073938439
Public PropertyPage As String
Attribute PropertyPage.VB_VarUserMemId = 1073938441
Public RequestEdit As Boolean
Attribute RequestEdit.VB_VarUserMemId = 1073938442
Public StandardMethod As Long
Attribute StandardMethod.VB_VarUserMemId = 1073938443
Public UIDefault As Boolean
Attribute UIDefault.VB_VarUserMemId = 1073938444

