//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubberduck.CodeAnalysis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class CodeInspectionDefaults : global::System.Configuration.ApplicationSettingsBase {
        
        private static CodeInspectionDefaults defaultInstance = ((CodeInspectionDefaults)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CodeInspectionDefaults())));
        
        public static CodeInspectionDefaults Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<CodeInspectionSettings xmlns:xsi=\"http:" +
            "//www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchem" +
            "a\">\r\n  <CodeInspections>\r\n    <CodeInspection Name=\"BooleanAssignedInIfElseInspe" +
            "ction\" Severity=\"Warning\" InspectionType=\"MaintainabilityAndReadabilityIssues\" /" +
            ">\r\n    <CodeInspection Name=\"ObsoleteErrorSyntaxInspection\" Severity=\"Suggestion" +
            "\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"StopKeywo" +
            "rdInspection\" Severity=\"Suggestion\" InspectionType=\"CodeQualityIssues\" />\r\n    <" +
            "CodeInspection Name=\"UnhandledOnErrorResumeNextInspection\" Severity=\"Warning\" In" +
            "spectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"EmptyStringLitera" +
            "lInspection\" Severity=\"Warning\" InspectionType=\"LanguageOpportunities\" />\r\n    <" +
            "CodeInspection Name=\"ImplicitByRefModifierInspection\" Severity=\"Hint\" Inspection" +
            "Type=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"FunctionReturnValueNotUse" +
            "dInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    <Code" +
            "Inspection Name=\"IllegalAnnotationInspection\" Severity=\"Error\" InspectionType=\"R" +
            "ubberduckOpportunities\" />\r\n    <CodeInspection Name=\"RedundantByRefModifierInsp" +
            "ection\" Severity=\"DoNotShow\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeIns" +
            "pection Name=\"MissingAttributeInspection\" Severity=\"Warning\" InspectionType=\"Rub" +
            "berduckOpportunities\" />\r\n    <CodeInspection Name=\"AttributeOutOfSyncInspection" +
            "\" Severity=\"Warning\" InspectionType=\"RubberduckOpportunities\" />\r\n    <CodeInspe" +
            "ction Name=\"MissingAnnotationArgumentInspection\" Severity=\"Error\" InspectionType" +
            "=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"MissingMemberAnnotationInspec" +
            "tion\" Severity=\"Error\" InspectionType=\"RubberduckOpportunities\" />\r\n    <CodeIns" +
            "pection Name=\"ModuleScopeDimKeywordInspection\" Severity=\"Suggestion\" InspectionT" +
            "ype=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"MultilineParameterInsp" +
            "ection\" Severity=\"Suggestion\" InspectionType=\"MaintainabilityAndReadabilityIssue" +
            "s\" />\r\n    <CodeInspection Name=\"MultipleDeclarationsInspection\" Severity=\"Warni" +
            "ng\" InspectionType=\"MaintainabilityAndReadabilityIssues\" />\r\n    <CodeInspection" +
            " Name=\"ObsoleteCallStatementInspection\" Severity=\"Suggestion\" InspectionType=\"La" +
            "nguageOpportunities\" />\r\n    <CodeInspection Name=\"ObsoleteCommentSyntaxInspecti" +
            "on\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeIn" +
            "spection Name=\"ObsoleteLetStatementInspection\" Severity=\"Suggestion\" InspectionT" +
            "ype=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"OptionBaseInspection\" " +
            "Severity=\"Hint\" InspectionType=\"MaintainabilityAndReadabilityIssues\" />\r\n    <Co" +
            "deInspection Name=\"RedundantOptionInspection\" Severity=\"Hint\" InspectionType=\"La" +
            "nguageOpportunities\" />\r\n    <CodeInspection Name=\"OptionExplicitInspection\" Sev" +
            "erity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"P" +
            "rocedureCanBeWrittenAsFunctionInspection\" Severity=\"Suggestion\" InspectionType=\"" +
            "LanguageOpportunities\" />\r\n    <CodeInspection Name=\"ApplicationWorksheetFunctio" +
            "nInspection\" Severity=\"Suggestion\" InspectionType=\"CodeQualityIssues\" />\r\n    <C" +
            "odeInspection Name=\"AssignedByValParameterInspection\" Severity=\"Warning\" Inspect" +
            "ionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"EmptyModuleInspection\"" +
            " Severity=\"Hint\" InspectionType=\"MaintainabilityAndReadabilityIssues\" />\r\n    <C" +
            "odeInspection Name=\"LineLabelNotUsedInspection\" Severity=\"Warning\" InspectionTyp" +
            "e=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"IntegerDataTypeInspection\" S" +
            "everity=\"Hint\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"" +
            "ShadowedDeclarationInspection\" Severity=\"DoNotShow\" InspectionType=\"CodeQualityI" +
            "ssues\" />\r\n    <CodeInspection Name=\"ConstantNotUsedInspection\" Severity=\"Warnin" +
            "g\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"DefaultProje" +
            "ctNameInspection\" Severity=\"Suggestion\" InspectionType=\"MaintainabilityAndReadab" +
            "ilityIssues\" />\r\n    <CodeInspection Name=\"EmptyCaseBlockInspection\" Severity=\"W" +
            "arning\" InspectionType=\"MaintainabilityAndReadabilityIssues\" />\r\n    <CodeInspec" +
            "tion Name=\"EmptyDoWhileBlockInspection\" Severity=\"Suggestion\" InspectionType=\"Ma" +
            "intainabilityAndReadabilityIssues\" />\r\n    <CodeInspection Name=\"EmptyElseBlockI" +
            "nspection\" Severity=\"Warning\" InspectionType=\"MaintainabilityAndReadabilityIssue" +
            "s\" />\r\n    <CodeInspection Name=\"EmptyForEachBlockInspection\" Severity=\"Warning\"" +
            " InspectionType=\"MaintainabilityAndReadabilityIssues\" />\r\n    <CodeInspection Na" +
            "me=\"EmptyForLoopBlockInspection\" Severity=\"Warning\" InspectionType=\"Maintainabil" +
            "ityAndReadabilityIssues\" />\r\n    <CodeInspection Name=\"EmptyIfBlockInspection\" S" +
            "everity=\"Warning\" InspectionType=\"MaintainabilityAndReadabilityIssues\" />\r\n    <" +
            "CodeInspection Name=\"EmptyWhileWendBlockInspection\" Severity=\"Warning\" Inspectio" +
            "nType=\"MaintainabilityAndReadabilityIssues\" />\r\n    <CodeInspection Name=\"Encaps" +
            "ulatePublicFieldInspection\" Severity=\"Suggestion\" InspectionType=\"Maintainabilit" +
            "yAndReadabilityIssues\" />\r\n    <CodeInspection Name=\"HostSpecificExpressionInspe" +
            "ction\" Severity=\"Warning\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeIn" +
            "spection Name=\"HungarianNotationInspection\" Severity=\"Suggestion\" InspectionType" +
            "=\"MaintainabilityAndReadabilityIssues\" />\r\n    <CodeInspection Name=\"ImplicitAct" +
            "iveSheetReferenceInspection\" Severity=\"Warning\" InspectionType=\"LanguageOpportun" +
            "ities\" />\r\n    <CodeInspection Name=\"ImplicitActiveWorkbookReferenceInspection\" " +
            "Severity=\"Warning\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeInspectio" +
            "n Name=\"ImplicitDefaultMemberAssignmentInspection\" Severity=\"Suggestion\" Inspect" +
            "ionType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"ImplicitPublicMemb" +
            "erInspection\" Severity=\"Hint\" InspectionType=\"LanguageOpportunities\" />\r\n    <Co" +
            "deInspection Name=\"ImplicitVariantReturnTypeInspection\" Severity=\"Hint\" Inspecti" +
            "onType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"MemberNotOnInterfac" +
            "eInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    <Code" +
            "Inspection Name=\"MoveFieldCloserToUsageInspection\" Severity=\"Hint\" InspectionTyp" +
            "e=\"MaintainabilityAndReadabilityIssues\" />\r\n    <CodeInspection Name=\"NonReturni" +
            "ngFunctionInspection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n  " +
            "  <CodeInspection Name=\"ObjectVariableNotSetInspection\" Severity=\"Error\" Inspect" +
            "ionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ObsoleteGlobalInspecti" +
            "on\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeIn" +
            "spection Name=\"ObsoleteTypeHintInspection\" Severity=\"Suggestion\" InspectionType=" +
            "\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"ParameterCanBeByValInspect" +
            "ion\" Severity=\"Suggestion\" InspectionType=\"MaintainabilityAndReadabilityIssues\" " +
            "/>\r\n    <CodeInspection Name=\"ParameterNotUsedInspection\" Severity=\"Warning\" Ins" +
            "pectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ProcedureNotUsedIn" +
            "spection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeIns" +
            "pection Name=\"SelfAssignedDeclarationInspection\" Severity=\"Suggestion\" Inspectio" +
            "nType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"UnassignedVariableUsageI" +
            "nspection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInsp" +
            "ection Name=\"UndeclaredVariableInspection\" Severity=\"Error\" InspectionType=\"Code" +
            "QualityIssues\" />\r\n    <CodeInspection Name=\"UntypedFunctionUsageInspection\" Sev" +
            "erity=\"Hint\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name" +
            "=\"UseMeaningfulNameInspection\" Severity=\"Suggestion\" InspectionType=\"Maintainabi" +
            "lityAndReadabilityIssues\" />\r\n    <CodeInspection Name=\"VariableNotAssignedInspe" +
            "ction\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspec" +
            "tion Name=\"VariableNotUsedInspection\" Severity=\"Warning\" InspectionType=\"CodeQua" +
            "lityIssues\" />\r\n    <CodeInspection Name=\"VariableTypeNotDeclaredInspection\" Sev" +
            "erity=\"Warning\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeInspection N" +
            "ame=\"WriteOnlyPropertyInspection\" Severity=\"Suggestion\" InspectionType=\"CodeQual" +
            "ityIssues\" />\r\n    <CodeInspection Name=\"DefTypeStatementInspection\" Severity=\"S" +
            "uggestion\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"" +
            "StepIsNotSpecifiedInspection\" Severity=\"DoNotShow\" InspectionType=\"LanguageOppor" +
            "tunities\" />\r\n    <CodeInspection Name=\"StepOneIsRedundantInspection\" Severity=\"" +
            "Hint\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"Sheet" +
            "AccessedUsingStringInspection\" Severity=\"Suggestion\" InspectionType=\"LanguageOpp" +
            "ortunities\" />\r\n    <CodeInspection Name=\"ObsoleteMemberUsageInspection\" Severit" +
            "y=\"Warning\" InspectionType=\"MaintainabilityAndReadabilityIssues\" />\r\n    <CodeIn" +
            "spection Name=\"ObsoleteCallingConventionInspection\" Severity=\"Warning\" Inspectio" +
            "nType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"DuplicatedAnnotationInsp" +
            "ection\" Severity=\"Error\" InspectionType=\"RubberduckOpportunities\" />\r\n    <CodeI" +
            "nspection Name=\"ModuleWithoutFolderInspection\" Severity=\"Suggestion\" InspectionT" +
            "ype=\"RubberduckOpportunities\" />\r\n    <CodeInspection Name=\"OnLocalErrorInspecti" +
            "on\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeIn" +
            "spection Name=\"IsMissingOnInappropriateArgumentInspection\" Severity=\"Warning\" In" +
            "spectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"IsMissingWithNonA" +
            "rgumentParameterInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues" +
            "\" />\r\n    <CodeInspection Name=\"AssignmentNotUsedInspection\" Severity=\"Suggestio" +
            "n\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"UnderscoreIn" +
            "PublicClassModuleMemberInspection\" Severity=\"Warning\" InspectionType=\"CodeQualit" +
            "yIssues\" />\r\n    <CodeInspection Name=\"ExcelUdfNameIsValidCellReferenceInspectio" +
            "n\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n  </CodeInspections" +
            ">\r\n  <WhitelistedIdentifiers />\r\n  <RunInspectionsOnSuccessfulParse>true</RunIns" +
            "pectionsOnSuccessfulParse>\r\n</CodeInspectionSettings>")]
        public global::Rubberduck.CodeAnalysis.Settings.CodeInspectionSettings CodeInspectionSettings {
            get {
                return ((global::Rubberduck.CodeAnalysis.Settings.CodeInspectionSettings)(this["CodeInspectionSettings"]));
            }
        }
    }
}
